# @author Madhavan Sridharan
name: Tag and Publish on Merge

on:
  # Trigger the workflow on push to the main branch
  push:
    branches:
      - main

jobs:
  release:
    name: Create Git Tag, GitHub Release, and Publish to npm
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance

    steps:
      - name: Debug NPM Token
        run: |
          if [ -z "$NPM_TOKEN" ]; then
            echo "NPM_TOKEN is not set. Exiting."
            exit 1
          else
            echo "NPM_TOKEN is set."
          fi
        env:
          NPM_TOKEN: ${{ secrets.NLXAI_NPM_TOKEN }}
      - name: Verify NPM Token
        env:
          NPM_TOKEN: ${{ secrets.NLXAI_NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          if [ "$(npm whoami --registry=https://registry.npmjs.org/)" == "" ]; then
            echo "Authentication failed. Exiting."
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies (including devDependencies)
        run: npm ci
        env:
          NODE_ENV: development

      # Optional: build if needed (for TypeScript, bundlers, etc.)
      - name: Build package
        run: npm run build

      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=v$(jq -r .version package.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Install semantic-release
        run: npm install -g semantic-release

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NLXAI_NPM_TOKEN }}
        run: npx semantic-release
