# @author Madhavan Sridharan
name: Tag and Publish on Merge

on:
  # Trigger the workflow on push to the main branch
  push:
    branches:
      - main

jobs:
  release:
    name: Create Git Tag, GitHub Release, and Publish to npm
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies (including devDependencies)
        run: |
          echo "registry=https://registry.npmjs.org/" >> ~/.npmrc
          npm ci
        env:
          NODE_ENV: development

      # Optional: build if needed (for TypeScript, bundlers, etc.)
      - name: Build package
        run: npm run build

      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=v$(jq -r .version package.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Install semantic-release
        run: npm install -g semantic-release

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NLXAI_CLASSIC_NPM_TOKEN }}
        run: |
          npx semantic-release
